spring:
  application:
    name: klage-dlt-consumer
  main:
    banner-mode: OFF
  codec:
    max-in-memory-size: 10MB

server:
  port: 7079
  error:
    whitelabel:
      enabled: false

navCallIdName: Nav-Callid

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    baggage:
      remote-fields:
        - ${navCallIdName}
      correlation:
        fields:
          - ${navCallIdName}
  prometheus:
    metrics:
      export:
        enabled: true

KAFKA_TOPIC: klage.privat-klage-mottatt-v1-dlt

SERVICE_USER_USERNAME: srvklage-dittnav

# 0 0 9,12,16 * * MON-FRI
DLT_CHECK_CRON: 0 0 9,12,13 * * MON-FRI