apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: klage-dlt-consumer
  namespace: klage
  labels:
    team: klage
spec:
  image: {{ image }}
  azure:
    application:
      enabled: true
  kafka:
    pool: {{kafka_pool}}
  port: 7079
  liveness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/prometheus
  webproxy: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
      {{#each externalHosts as |host|}}
        - host: {{host}}
      {{/each}}
  envFrom:
    - secret: srvklage-dittnav
    - secret: slack-url
    - secret: slack-channel-id
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
