externalHosts:
  - a01apvl00145.adeo.no
  - a01apvl00146.adeo.no
  - a01apvl00147.adeo.no
  - a01apvl00148.adeo.no
  - a01apvl00149.adeo.no
  - a01apvl00150.adeo.no
  - hooks.slack.com
springProfile: prod-gcp
kafka_pool: nav-prod



